# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20161206_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ('created',)},
        ),
    ]
